export * from "./auth.service";
export * from "./group.service.ts";
export * from "./courses.service.ts";
export * from "./student.service.ts";
export * from "./teacher.service.ts";
export * from "./branches.service.ts";
export * from "./rooms.service.ts";
export * from "./lesson.service.ts"
export * from "./general.service.ts"